In [1]:
import pandas as pd
df1 = pd.read_csv('SWWQDiscovery_clean.csv')
df2 = pd.read_csv('SWActiveSites_fishing.csv')

In [2]:
df2

,STATION,STNAME,SHORTNAME,GAUGE,DATUM,CATCHAREA,ZONE,EASTING,NORTHING,GRDATUM,...,ELEV,ELEVACC,FIELD,LAB,ACTIVE,COMMENCED,CEASED,REGION,FISHING,FISH
0,221001,GENOA RIVER @ ROCKTON,GENOA R @ ROCKTON,414.716,AHD,125.6,55,705825.000,5887218.000,UTM,...,429.0,1,Y,Y,1,1993-05-26,NaN,221,1,"bream, estuary perch, bass"
1,221201,CANN RIVER (WEST BRANCH) @ WEERAGUA,CANN (WB) @ WEERAGUA,153.956,AHD,311.0,55,694682.000,5861473.000,UTM,...,169.0,1,Y,Y,1,1922-04-22,NaN,221,0,NaN
2,221207,ERRINUNDRA RIVER @ ERRINUNDRA,ERRINUNDRA @ ERRINUN,0.000,GAU,162.0,55,669418.000,5853798.000,UTM,...,168.0,1,n,n,1,1968-02-20,NaN,221,0,NaN
3,221208,WINGAN RIVER @ WINGAN INLET NATIONAL PARK,WINGAN @WINGAN INLET,0.000,ARB,420.0,55,719710.300,5825779.500,UTM,...,50.0,1,Y,Y,1,1979-06-22,NaN,221,0,NaN
4,221209,CANN RIVER (EAST BRANCH) @ WEERAGUA,CANN (EBR) WEERAGUA,0.000,NaN,154.0,55,695470.000,5863398.000,UTM,...,202.0,1,Y,N,1,1972-10-23,NaN,221,0,NaN
5,221210,GENOA RIVER @ THE GORGE,GENOA @ GORGE,0.000,NaN,837.0,55,723046.000,5856007.000,UTM,...,102.0,1,Y,Y,1,1972-08-22,NaN,221,1,"bream, estuary perch, bass"
6,221211,COMBIENBAR RIVER @ COMBIENBAR,COMBIENBAR @ COMB.,0.000,GAU,179.0,55,675439.000,5854433.000,UTM,...,189.0,1,Y,Y,1,1974-08-12,NaN,221,0,NaN
7,221212,BEMM RIVER @ PRINCES HIGHWAY,BEMM @ PRINCES HWY,0.000,NaN,725.0,55,667855.000,5836059.000,UTM,...,82.0,1,Y,Y,1,1975-04-30,NaN,221,1,"flathead, bream, bass, estuary perch"
8,221218,BETKA RIVER @ MINERS TRACK,BETKA R @ MINERS TRK,0.000,ARB,0.0,55,732688.000,5835801.000,UTM,...,0.0,1,N,N,1,1996-01-16,NaN,221,0,NaN
9,221224,CANN RIVER U/S CANN RIVER OFFTAKE,CANN RV U/S O/TAKE,0.000,NaN,0.0,55,690544.000,5843171.000,UTM,...,0.0,NaN,y,N,1,2009-03-11,NaN,221,0,NaN
10,221225,BEMM RIVER U/S OF PUMPHOUSE,BEMM R U/S PUMPHOUSE,0.000,NaN,0.0,55,671929.000,5822377.000,UTM,...,0.0,NaN,N,N,1,2009-09-23,NaN,221,1,"flathead, bream, bass, estuary perch"
11,221800,RAINGAUGE (GENOA RIVER) @ THE GORGE,RG @ THE GORGE,0.000,ARB,0.0,55,722715.000,5855916.400,NaN,...,0.0,1,N,N,1,1972-08-22,1992-10-01 00:00:00.000,221,1,"bream, estuary perch, bass"
12,222200,SNOWY RIVER @ JARRAHMOND,SNOWY R @ JARRAHMOND,0.000,AHD,13421.0,55,620071.000,5830901.000,UTM,...,27.0,1,Y,Y,1,1889-04-01,NaN,222,0,NaN
13,222201,SNOWY RIVER @ ORBOST,SNOWY R @ ORBOST,-0.141,AHD,13572.0,55,627898.000,5825644.400,UTM,...,7.0,1,Y,Y,1,1907-04-13,NaN,222,0,NaN
14,222202,BRODRIBB RIVER @ SARDINE CREEK,BRODRIBB @ SARDINE,78.591,AHD,658.0,55,636752.000,5847240.000,UTM,...,103.0,1,Y,N,1,1922-04-24,NaN,222,0,NaN
15,222203,SNOWY RIVER @ MARLO JETTY,SNOWY @ MARLO JETTY,-0.745,AHD,0.0,55,634504.800,5815384.500,NaN,...,0.0,1,N,N,1,1934-06-25,NaN,222,0,NaN
16,222205,SNOWY RIVER @ NEWMERELLA-LOCHEND ROAD,SNOWY @ NEWMERELLA,-0.479,ARB,13600.0,55,633887.775,5820634.951,MGA94,...,0.0,1,N,N,1,1960-03-01,NaN,222,0,NaN
17,222206,BUCHAN RIVER @ BUCHAN,BUCHAN @ BUCHAN,74.850,AHD,822.0,55,603711.000,5849459.000,UTM,...,90.0,9,Y,Y,1,1926-03-27,NaN,222,0,NaN
18,222209,SNOWY RIVER @ MCKILLOP BRIDGE,SNOWY @ MCKILLOP BR.,0.000,ARB,10619.0,55,625612.000,5894902.000,UTM,...,174.0,9,Y,Y,1,1941-03-01,NaN,222,0,NaN
19,222210,DEDDICK RIVER @ DEDDICK (CASEYS),DEDDICK @ DEDDICK,0.000,ARB,857.0,55,626577.700,5894693.700,UTM,...,0.0,1,Y,N,1,1964-03-26,NaN,222,0,NaN
20,222213,SUGGAN BUGGAN RIVER @ SUGGAN BUGGAN,S.BUGGAN @ SUGGAN,0.000,ARB,357.0,55,618048.000,5909278.000,UTM,...,0.0,1,Y,N,1,1957-07-24,NaN,222,0,NaN
21,222217,RODGER RIVER @ JACKSONS CROSSING,RODGER @ JACKSONS,0.000,ARB,447.0,55,620346.000,5858744.000,UTM,...,0.0,1,Y,Y,1,1976-06-03,NaN,222,0,NaN
22,222219,SNOWY RIVER @ D/S OF BASIN CREEK,SNOWY @ BASIN CRK,0.000,ARB,11964.0,55,612580.000,5848984.000,UTM,...,0.0,1,Y,Y,1,1978-12-12,NaN,222,0,NaN
23,222221,BUCHAN RIVER @ EGW OFFTAKE,BUCHAN R @ EGW O/T,0.000,NaN,0.0,55,603874.000,5852271.000,UTM,...,0.0,NaN,y,N,1,2009-05-14,NaN,222,0,NaN
24,222222,ROCKY RIVER U/S OT THE WEIR,ROCKY RIVER U/S OT T,0.000,NaN,0.0,55,645938.000,5834053.000,UTM,...,0.0,NaN,y,N,1,2009-03-11,NaN,222,0,NaN
25,223202,TAMBO RIVER @ SWIFTS CREEK,TAMBO @ SWIFTS CREEK,280.863,AHD,943.0,55,564619.000,5875047.000,UTM,...,305.0,1,Y,Y,1,1937-06-01,NaN,223,1,"bream, luderick, flathead, mulloway"
26,223204,NICHOLSON RIVER @ DEPTFORD,NICHOLSON @ DEPTFORD,0.000,ARB,287.0,55,561543.000,5839104.000,UTM,...,0.0,1,Y,Y,1,1961-05-12,NaN,223,0,NaN
27,223205,TAMBO RIVER @ D/S OF RAMROD CREEK,TAMBO @ DS RAMROD,15.452,AHD,2681.0,55,576710.000,5830147.000,UTM,...,0.0,1,Y,N,1,1965-06-09,NaN,223,1,"bream, luderick, flathead, mulloway"
28,223209,TAMBO RIVER @ BATTENS LANDING,TAMBO @ BATTENS,0.000,ARB,2781.0,55,574796.100,5820757.900,UTM,...,0.0,1,Y,N,1,1977-01-26,NaN,223,1,"bream, luderick, flathead, mulloway"
29,223210,NICHOLSON RIVER @ SARSFIELD,NICHOLSON @ SARSFIEL,0.000,ARB,471.0,55,562646.000,5823050.000,UTM,...,42.0,1,Y,Y,1,1977-09-21,NaN,223,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
889,415244,SHEPHERDS CREEK @ WARRAK,SHEPHERDS C @ WARRAK,0.000,ARB,6.0,54,693864.000,5874762.000,UTM,...,0.0,1,Y,N,1,1983-09-07,NaN,415,0,NaN
890,415245,MOUNT COLE CREEK @ CROWLANDS,MT COLE @ CROWLANDS,0.000,ARB,144.0,54,685889.000,5884771.000,UTM,...,0.0,1,Y,N,1,1985-04-29,NaN,415,0,NaN
891,415246,WIMMERA RIVER @ LOCHIEL RAILWAY BRIDGE,WIMMERA @ LOCHIEL,0.000,ARB,0.0,54,587370.000,5970298.000,UTM,...,0.0,1,Y,Y,1,1987-02-27,NaN,415,0,NaN
892,415247,WIMMERA RIVER @ TARRANYURK,WIMMERA @ TARRANYURK,0.000,ARB,0.0,54,589795.000,5992934.000,UTM,...,0.0,1,Y,N,1,1987-02-26,NaN,415,0,NaN
893,415250,FYANS CREEK @ FYANS CREEK,FYANS @ FYANS,0.000,ARB,145.0,54,638554.409,5892046.933,UTM,...,0.0,1,Y,N,1,1988-08-09,NaN,415,0,NaN
894,415251,MACKENZIE RIVER @ MCKENZIE CREEK,MACKENZIE @ MCKENZIE,0.000,ARB,351.0,54,605199.000,5925738.000,UTM,...,0.0,1,Y,Y,1,1988-08-24,NaN,415,0,NaN
895,415252,MOUNT WILLIAM CREEK @ MOKEPILLY,MT WILLIAM MOKEPILLY,0.000,ARB,628.0,54,644542.000,5893169.000,UTM,...,0.0,1,Y,N,1,1980-09-20,NaN,415,0,NaN
896,415256,WIMMERA RIVER @ U/S OF DIMBOOLA,WIMMERA U/S DIMBOOLA,0.000,NaN,0.0,54,590370.000,5953407.000,UTM,...,0.0,1,Y,N,1,1989-04-19,NaN,415,0,NaN
897,415257,RICHARDSON RIVER @ DONALD,RICHARDSON @ DONALD,0.000,ARB,1831.0,54,677870.000,5966690.000,UTM,...,0.0,1,Y,Y,1,1989-05-03,NaN,415,0,NaN
898,415259,RICHARDSON RIVER @ BANYENA,RICHARDSON @ BANYENA,0.000,ARB,1786.0,54,663334.000,5951116.000,UTM,...,0.0,1,N,Y,1,1993-05-25,NaN,415,0,NaN
899,415260,RICHARDSON RIVER @ U/S RICHAVON WEIR,RICHARDSON @ U/S WEI,0.000,NaN,0.0,54,668460.000,5958440.000,UTM,...,0.0,1,Y,N,1,1993-06-17,NaN,415,0,NaN
900,415261,WIMMERA RIVER @ QUANTONG,WIMMERA R @ QUANTONG,110.010,AHD,0.0,54,589574.000,5934219.000,UTM,...,0.0,1,Y,N,1,1993-01-29,NaN,415,0,NaN
901,415273,NORTON CREEK @ LOWER NORTON,NORTON @ LWR NORTON,0.000,ARB,0.0,54,595838.698,5928906.153,ANG,...,0.0,1,Y,N,1,2008-01-11,NaN,415,0,NaN
902,415275,FRANKS GULLY CREEK @ LANDSBOROUGH RES. H.G.,LANDSBOROUGH RES HG,NaN,NaN,NaN,54,690274.000,5899735.000,AMG84,...,282.0,NaN,N,N,1,2009-06-16,NaN,415,0,NaN
903,415600,LAKE HINDMARSH @ JEPARIT,LAKE HINDMARSH,73.750,AHD,0.0,54,585903.000,6001127.000,UTM,...,80.0,9,Y,N,1,1960-04-02,NaN,415,0,NaN
904,415601,LAKE ALBACUTYA @ RAINBOW,LAKE ALBACUTYA,0.000,ARB,0.0,54,586095.000,6037447.000,UTM,...,0.0,1,Y,N,1,1899-12-30,NaN,415,0,NaN
905,415602,LAKE NATIMUK @ HORSHAM,LAKE NATIMUK,0.000,ARB,0.0,54,584026.000,5936251.000,UTM,...,0.0,1,Y,N,1,1899-12-30,NaN,415,0,NaN
906,415604,LAKE BULOKE @ DONALD,LAKE BULOKE,0.000,NaN,0.0,54,678371.300,5980454.100,MGA94,...,0.0,1,Y,N,1,1899-12-30,NaN,415,0,NaN
907,415608,TAYLORS LAKE,Taylors Lake,0.000,NaN,0.0,54,623083.000,5930331.000,UTM,...,0.0,1,N,N,1,1992-01-22,NaN,415,0,NaN
908,415610,LAKE FYANS,LAKE FYANS,0.000,NaN,0.0,54,643052.000,5888945.000,UTM,...,0.0,1,N,N,1,1992-01-22,NaN,415,0,NaN
909,415612,GREEN LAKE (NEAR HORSHAM),Green Lake,NaN,NaN,NaN,54,615133.000,5927923.000,UTM,...,0.0,1,N,N,1,1992-01-22,NaN,415,0,NaN
910,415620,LAKE TOOLONDO HG @ LAKE TOOLONDO,TOOLONDO HG,NaN,NaN,NaN,0,0.000,0.000,NaN,...,0.0,NOT,Y,N,1,2019-01-01,NaN,415,0,NaN
911,415704,WANNON DIVERSION PIPELINE @ OUTLET,WANNON DIV. PIPELINE,419.512,AHD,0.0,54,636340.948,5872154.794,UTM,...,0.0,1,Y,N,1,1971-04-17,NaN,415,0,NaN
912,415705,BYPASS CHANNEL @ LAKE LONSDALE,BYPASS CH L LONSDALE,0.000,NaN,0.0,54,640993.000,5900137.000,UTM,...,0.0,1,Y,N,1,1967-12-06,NaN,415,0,NaN
913,415707,WIMMERA INLET CHANNEL @ MCKENZIES DROP,WIMMERA INLET CHANNL,NaN,NaN,NaN,54,624354.279,5922512.886,MGA94,...,150.0,9,N,N,1,1968-05-23,NaN,415,0,NaN
914,415800,WEATHER STATION @ WARTOOK RESERVOIR,WEATHER ST. WARTOOK,NaN,NaN,NaN,54,627489.000,5893794.000,UTM,...,0.0,NaN,Y,N,1,2009-05-22,NaN,415,0,NaN
915,415801,WEATHER STATION @ BELLFIELD RESERVOIR,WEATHER ST BELLFIELD,NaN,NaN,NaN,54,637389.486,5884771.699,UTM,...,0.0,NaN,Y,N,1,2011-01-01,NaN,415,0,NaN
916,425017,DARLING RIVER @ WENTWORTH,DARLING @ WENTWORTH,0.000,NaN,0.0,54,584281.000,6227127.000,UTM,...,40.0,9,Y,N,1,1992-05-06,NaN,414,0,NaN
917,426200,MURRAY RIVER @ BELOW RUFUS RIVER. OPERATIONAL ...,MURRAY - RUFUS RIVER,16.932,AHD,0.0,54,522588.984,6230908.046,NaN,...,0.0,1,Y,N,1,1968-04-05,NaN,414,0,NaN
918,426502,RUFUS RIVER @ LAKE VICTORIA OUTLET,RUFUS @ VICTORIA O/L,0.000,NaN,0.0,54,525506.000,6232364.000,UTM,...,0.0,1,n,y,1,1899-12-30,NaN,414,0,NaN

In [3]:
# merge the datasets
df3 = df2[['STATION', 'STNAME', 'LATITUDE', 'LONGITUDE', 'FISHING', 'FISH']]
df4 = pd.merge(df1, df3, how='left', on='STATION')

In [4]:
# drop NaN and reset index
df4 = df4.dropna(subset=['CurrentSite'])
df4 = df4.reset_index()
df4 = df4.drop('index', 1)
df4

,STATION,CurrentSite,Field pH,Field DO,Field Temp,Field SampTemp,Field AirTemp,Field SampDepth,Field Turb,Field EC,...,Cations,TOC,DOC,Chlorophyll-a,Phaeophytin,STNAME,LATITUDE,LONGITUDE,FISHING,FISH
0,221001,*,319,312,0,0,0,315,331,0,...,0,0,0,0,0,GENOA RIVER @ ROCKTON,-37.138655,149.317296,1.0,"bream, estuary perch, bass"
1,221201,*,360,354,0,0,0,358,372,0,...,0,2,0,0,0,CANN RIVER (WEST BRANCH) @ WEERAGUA,-37.372936,149.198661,0.0,NaN
2,221207,*,464,457,0,0,0,464,476,0,...,0,0,0,0,0,ERRINUNDRA RIVER @ ERRINUNDRA,-37.447037,148.915256,0.0,NaN
3,221208,*,345,339,0,0,0,344,357,0,...,0,0,0,0,0,WINGAN RIVER @ WINGAN INLET NATIONAL PARK,-37.688768,149.491767,0.0,NaN
4,221209,*,192,192,0,0,0,192,192,0,...,0,0,0,0,0,CANN RIVER (EAST BRANCH) @ WEERAGUA,-37.355431,149.207046,0.0,NaN
5,221210,*,362,355,0,0,0,360,374,0,...,0,2,0,0,0,GENOA RIVER @ THE GORGE,-37.415771,149.520376,1.0,"bream, estuary perch, bass"
6,221211,*,224,221,0,0,0,222,233,0,...,0,0,0,0,0,COMBIENBAR RIVER @ COMBIENBAR,-37.440194,148.983135,0.0,NaN
7,221212,*,362,355,0,0,0,359,372,0,...,0,2,0,0,0,BEMM RIVER @ PRINCES HIGHWAY,-37.607126,148.901649,1.0,"flathead, bream, bass, estuary perch"
8,222200,*,361,353,0,0,0,359,374,0,...,0,1,0,0,0,SNOWY RIVER @ JARRAHMOND,-37.661086,148.361314,0.0,NaN
9,222201,*,96,96,0,0,0,96,96,0,...,0,0,0,0,0,SNOWY RIVER @ ORBOST,-37.707393,148.450950,0.0,NaN
10,222202,*,362,355,0,0,0,359,375,0,...,0,1,0,0,0,BRODRIBB RIVER @ SARDINE CREEK,-37.511534,148.547325,0.0,NaN
11,222206,*,313,308,0,0,0,311,325,0,...,0,2,0,0,0,BUCHAN RIVER @ BUCHAN,-37.495843,148.173242,0.0,NaN
12,222209,*,361,357,0,0,0,359,373,0,...,0,0,0,0,0,SNOWY RIVER @ MCKILLOP BRIDGE,-37.083628,148.413255,0.0,NaN
13,222210,*,277,277,0,0,0,276,277,0,...,0,0,0,0,0,DEDDICK RIVER @ DEDDICK (CASEYS),-37.085375,148.424152,0.0,NaN
14,222213,*,272,272,0,0,0,272,272,0,...,0,0,0,0,0,SUGGAN BUGGAN RIVER @ SUGGAN BUGGAN,-36.955055,148.325921,0.0,NaN
15,222217,*,346,338,0,0,0,342,359,0,...,0,0,0,0,0,RODGER RIVER @ JACKSONS CROSSING,-37.410156,148.359867,0.0,NaN
16,222219,*,175,174,0,0,0,174,179,0,...,0,0,0,0,0,SNOWY RIVER @ D/S OF BASIN CREEK,-37.499085,148.273625,0.0,NaN
17,223202,*,362,364,0,0,0,362,378,0,...,0,2,0,0,0,TAMBO RIVER @ SWIFTS CREEK,-37.268781,147.728819,1.0,"bream, luderick, flathead, mulloway"
18,223204,*,346,349,0,0,0,346,362,0,...,0,0,0,0,0,NICHOLSON RIVER @ DEPTFORD,-37.592946,147.697124,0.0,NaN
19,223205,*,276,276,0,0,0,276,276,0,...,0,42,0,0,0,TAMBO RIVER @ D/S OF RAMROD CREEK,-37.672531,147.869851,1.0,"bream, luderick, flathead, mulloway"
20,223209,*,17,17,0,0,0,17,17,0,...,0,0,0,0,0,TAMBO RIVER @ BATTENS LANDING,-37.757306,147.849116,1.0,"bream, luderick, flathead, mulloway"
21,223210,*,627,627,0,0,0,629,681,0,...,0,0,0,0,0,NICHOLSON RIVER @ SARSFIELD,-37.737562,147.710996,0.0,NaN
22,223212,*,196,196,0,0,0,196,196,0,...,0,0,0,0,0,TIMBARRA RIVER @ D/S OF WILKINSON CREEK,-37.446318,148.063434,0.0,NaN
23,223214,*,359,361,0,0,0,359,373,0,...,0,0,0,0,0,TAMBO RIVER @ U/S OF SMITH CREEK,-36.954707,147.927640,1.0,"bream, luderick, flathead, mulloway"
24,223215,*,96,96,0,0,0,96,97,0,...,0,0,0,0,0,HAUNTED STREAM @ HELLS GATE,-37.481387,147.825839,0.0,NaN
25,224200,*,4,4,0,0,0,4,5,0,...,0,0,0,0,0,MITCHELL RIVER @ BAIRNSDALE,-37.826386,147.593617,1.0,bream
26,224201,*,179,179,0,0,0,179,179,0,...,0,43,0,0,0,WONNANGATTA RIVER @ WATERFORD,-37.489961,147.166444,0.0,NaN
27,224203,*,361,363,0,0,0,361,376,0,...,0,2,0,0,0,MITCHELL RIVER @ GLENALADALE,-37.763590,147.374778,1.0,bream
28,224206,*,355,358,0,0,0,358,371,0,...,0,2,0,0,0,WONNANGATTA RIVER @ CROOKED RIVER,-37.407497,147.089165,0.0,NaN
29,224213,*,358,362,0,0,0,360,375,0,...,0,0,0,0,0,DARGO RIVER @ LOWER DARGO ROAD,-37.495118,147.268699,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
388,414716,*,36,35,0,0,0,36,36,0,...,0,0,0,0,0,ROBINVALE NO 4 SYSTEM OUTFALL @ PETHARD ROAD,-34.604459,142.740714,0.0,NaN
389,414717,*,36,35,0,0,0,36,36,0,...,0,0,0,0,0,ROBINVALE NO 6 SYSTEM OUTFALL @ MALAYA ROAD,-34.636635,142.701383,0.0,NaN
390,414721,*,24,24,0,0,0,24,24,0,...,0,0,0,0,0,NANGILOC-COLIGNAN DRAIN @ HEWETTS ROAD,-34.508705,142.380673,0.0,NaN
391,414723,*,23,23,0,0,0,23,23,0,...,0,0,0,0,0,KULKYNE OUTFALL DRAIN @ MANSELLS PUMP,-34.560305,142.407139,0.0,NaN
392,414724,*,24,24,0,0,0,24,24,0,...,0,0,0,0,0,NANGILOC COLIGNAN DRAIN @ NANGILOC,-34.470270,142.353582,0.0,NaN
393,414728,*,24,24,0,0,0,24,24,0,...,0,0,0,0,0,BROWN'S GROUP DRAINAGE AREA @ BROWN'S ROAD,-34.548737,142.388222,0.0,NaN
394,415200,*,363,362,0,0,0,360,363,0,...,0,2,0,0,0,WIMMERA RIVER @ HORSHAM,-36.739911,142.147163,0.0,NaN
395,415201,*,470,470,0,0,0,470,470,0,...,0,42,0,0,0,WIMMERA RIVER @ GLENORCHY WEIR TAIL GAUGE,-36.909300,142.642970,0.0,NaN
396,415202,*,153,153,0,0,0,153,174,0,...,0,0,0,0,0,MACKENZIE RIVER @ WARTOOK RESERVOIR,-37.107641,142.424437,0.0,NaN
397,415203,*,323,325,0,0,0,323,326,0,...,0,0,0,0,0,MOUNT WILLIAM CREEK @ LAKE LONSDALE (TAIL GAUGE),-37.030570,142.583590,0.0,NaN
398,415207,*,358,358,0,0,0,357,358,0,...,0,0,0,0,0,WIMMERA RIVER @ EVERSLEY,-37.185039,143.184627,0.0,NaN
399,415214,*,178,178,0,0,0,178,178,0,...,0,0,0,0,0,FYANS CREEK @ LAKE BELLFIELD,-37.169610,142.542150,0.0,NaN
400,415217,*,173,173,0,0,0,173,173,0,...,0,0,0,0,0,FYANS CREEK @ GRAMPIANS ROAD BRIDGE,-37.250863,142.535748,0.0,NaN
401,415220,*,257,257,0,0,0,257,257,0,...,0,0,0,0,0,AVON RIVER @ WIMMERA HIGHWAY,-36.640580,142.978650,0.0,NaN
402,415227,*,0,0,0,0,0,0,102,0,...,0,0,0,0,0,MOUNT WILLIAM CREEK @ LAKE LONSDALE (HEAD GAUGE),-37.030225,142.586322,0.0,NaN
403,415228,*,0,0,0,0,0,3,70,0,...,0,0,0,0,0,MACKENZIE RIVER @ WARTOOK RESERVOIR (HEAD GAUGE),-37.093464,142.434475,0.0,NaN
404,415229,*,0,0,0,0,0,3,68,0,...,0,0,0,0,0,FYANS CREEK @ LAKE BELLFIELD (HEAD GAUGE),-37.173750,142.547372,0.0,NaN
405,415237,*,275,275,0,0,0,275,276,0,...,0,0,0,0,0,CONCONGELLA CREEK @ STAWELL,-37.025743,142.821776,0.0,NaN
406,415246,*,335,334,0,0,0,333,335,0,...,0,0,0,0,0,WIMMERA RIVER @ LOCHIEL RAILWAY BRIDGE,-36.408395,141.974435,0.0,NaN
407,415251,*,210,211,0,0,0,215,210,0,...,0,0,0,0,0,MACKENZIE RIVER @ MCKENZIE CREEK,-36.808231,142.179346,0.0,NaN
408,415257,*,254,257,0,0,0,254,257,0,...,0,0,0,0,0,RICHARDSON RIVER @ DONALD,-36.428406,142.984198,0.0,NaN
409,415259,*,164,165,0,0,0,164,164,0,...,0,0,0,0,0,RICHARDSON RIVER @ BANYENA,-36.571321,142.825413,0.0,NaN
410,415600,*,136,136,0,0,0,128,132,0,...,0,0,4,0,0,LAKE HINDMARSH @ JEPARIT,-36.130627,141.954686,0.0,NaN
411,415601,*,101,101,0,0,0,101,101,0,...,0,0,0,0,0,LAKE ALBACUTYA @ RAINBOW,-35.803196,141.952877,0.0,NaN
412,415602,*,63,63,0,0,0,50,59,0,...,0,0,11,0,0,LAKE NATIMUK @ HORSHAM,-36.715588,141.940858,0.0,NaN
413,415604,*,46,46,0,0,0,46,46,0,...,0,0,0,0,0,LAKE BULOKE @ DONALD,-36.304300,142.986630,0.0,NaN
414,415608,*,12,12,0,0,0,16,198,0,...,0,0,0,0,0,TAYLORS LAKE,-36.764681,142.379046,0.0,NaN
415,415610,*,0,0,0,0,0,3,185,0,...,0,0,0,0,0,LAKE FYANS,-37.134804,142.610542,0.0,NaN
416,415612,*,0,0,0,0,0,0,119,0,...,0,0,0,0,0,GREEN LAKE (NEAR HORSHAM),-36.787382,142.290357,0.0,NaN
417,426200,*,162,162,0,0,0,162,162,0,...,0,45,0,0,0,MURRAY RIVER @ BELOW RUFUS RIVER. OPERATIONAL ...,-34.062193,141.244785,0.0,NaN

In [5]:
# split the STNAME
split_data = df4["STNAME"].str.split(" @ ")
data = list(split_data)
names = ["RIVER", "LOCATION"]
new_df = pd.DataFrame(data, columns=names)
new_df.fillna(value=pd.np.nan, inplace=True)
print(new_df)

                             RIVER                               LOCATION
0                      GENOA RIVER                                ROCKTON
1         CANN RIVER (WEST BRANCH)                               WEERAGUA
2                 ERRINUNDRA RIVER                             ERRINUNDRA
3                     WINGAN RIVER             WINGAN INLET NATIONAL PARK
4         CANN RIVER (EAST BRANCH)                               WEERAGUA
5                      GENOA RIVER                              THE GORGE
6                 COMBIENBAR RIVER                             COMBIENBAR
7                       BEMM RIVER                        PRINCES HIGHWAY
8                      SNOWY RIVER                             JARRAHMOND
9                      SNOWY RIVER                                 ORBOST
10                  BRODRIBB RIVER                          SARDINE CREEK
11                    BUCHAN RIVER                                 BUCHAN
12                     SNOWY RIVER                        MCKILLOP BRIDGE
13                   DEDDICK RIVER                       DEDDICK (CASEYS)
14             SUGGAN BUGGAN RIVER                          SUGGAN BUGGAN
15                    RODGER RIVER                      JACKSONS CROSSING
16                     SNOWY RIVER                     D/S OF BASIN CREEK
17                     TAMBO RIVER                           SWIFTS CREEK
18                 NICHOLSON RIVER                               DEPTFORD
19                     TAMBO RIVER                    D/S OF RAMROD CREEK
20                     TAMBO RIVER                        BATTENS LANDING
21                 NICHOLSON RIVER                              SARSFIELD
22                  TIMBARRA RIVER                 D/S OF WILKINSON CREEK
23                     TAMBO RIVER                     U/S OF SMITH CREEK
24                  HAUNTED STREAM                             HELLS GATE
25                  MITCHELL RIVER                             BAIRNSDALE
26               WONNANGATTA RIVER                              WATERFORD
27                  MITCHELL RIVER                            GLENALADALE
28               WONNANGATTA RIVER                          CROOKED RIVER
29                     DARGO RIVER                       LOWER DARGO ROAD
..                             ...                                    ...
388  ROBINVALE NO 4 SYSTEM OUTFALL                           PETHARD ROAD
389  ROBINVALE NO 6 SYSTEM OUTFALL                            MALAYA ROAD
390        NANGILOC-COLIGNAN DRAIN                           HEWETTS ROAD
391          KULKYNE OUTFALL DRAIN                          MANSELLS PUMP
392        NANGILOC COLIGNAN DRAIN                               NANGILOC
393    BROWN'S GROUP DRAINAGE AREA                           BROWN'S ROAD
394                  WIMMERA RIVER                                HORSHAM
395                  WIMMERA RIVER              GLENORCHY WEIR TAIL GAUGE
396                MACKENZIE RIVER                      WARTOOK RESERVOIR
397            MOUNT WILLIAM CREEK             LAKE LONSDALE (TAIL GAUGE)
398                  WIMMERA RIVER                               EVERSLEY
399                    FYANS CREEK                         LAKE BELLFIELD
400                    FYANS CREEK                  GRAMPIANS ROAD BRIDGE
401                     AVON RIVER                        WIMMERA HIGHWAY
402            MOUNT WILLIAM CREEK             LAKE LONSDALE (HEAD GAUGE)
403                MACKENZIE RIVER         WARTOOK RESERVOIR (HEAD GAUGE)
404                    FYANS CREEK            LAKE BELLFIELD (HEAD GAUGE)
405              CONCONGELLA CREEK                                STAWELL
406                  WIMMERA RIVER                 LOCHIEL RAILWAY BRIDGE
407                MACKENZIE RIVER                         MCKENZIE CREEK
408               RICHARDSON RIVER                                 DONALD
409               RICHARDSON RIVER                                BANYENA
410                 LAKE HINDMARSH                                JEPARIT
411                 LAKE ALBACUTYA                                RAINBOW
412                   LAKE NATIMUK                                HORSHAM
413                    LAKE BULOKE                                 DONALD
414                   TAYLORS LAKE                                    NaN
415                     LAKE FYANS                                    NaN
416      GREEN LAKE (NEAR HORSHAM)                                    NaN
417                   MURRAY RIVER  BELOW RUFUS RIVER. OPERATIONAL TABLES

[418 rows x 2 columns]

In [7]:
# update the data
df4['STNAME'] = new_df['RIVER']
df4['LOCATION'] = new_df['LOCATION']
df4['FISHING'] = df4['FISHING'].astype(int)
df4['FISH'] = df4['FISH'].str.capitalize()
df4

,STATION,CurrentSite,Field pH,Field DO,Field Temp,Field SampTemp,Field AirTemp,Field SampDepth,Field Turb,Field EC,...,TOC,DOC,Chlorophyll-a,Phaeophytin,STNAME,LATITUDE,LONGITUDE,FISHING,FISH,LOCATION
0,221001,*,319,312,0,0,0,315,331,0,...,0,0,0,0,GENOA RIVER,-37.138655,149.317296,1,"Bream, estuary perch, bass",ROCKTON
1,221201,*,360,354,0,0,0,358,372,0,...,2,0,0,0,CANN RIVER (WEST BRANCH),-37.372936,149.198661,0,NaN,WEERAGUA
2,221207,*,464,457,0,0,0,464,476,0,...,0,0,0,0,ERRINUNDRA RIVER,-37.447037,148.915256,0,NaN,ERRINUNDRA
3,221208,*,345,339,0,0,0,344,357,0,...,0,0,0,0,WINGAN RIVER,-37.688768,149.491767,0,NaN,WINGAN INLET NATIONAL PARK
4,221209,*,192,192,0,0,0,192,192,0,...,0,0,0,0,CANN RIVER (EAST BRANCH),-37.355431,149.207046,0,NaN,WEERAGUA
5,221210,*,362,355,0,0,0,360,374,0,...,2,0,0,0,GENOA RIVER,-37.415771,149.520376,1,"Bream, estuary perch, bass",THE GORGE
6,221211,*,224,221,0,0,0,222,233,0,...,0,0,0,0,COMBIENBAR RIVER,-37.440194,148.983135,0,NaN,COMBIENBAR
7,221212,*,362,355,0,0,0,359,372,0,...,2,0,0,0,BEMM RIVER,-37.607126,148.901649,1,"Flathead, bream, bass, estuary perch",PRINCES HIGHWAY
8,222200,*,361,353,0,0,0,359,374,0,...,1,0,0,0,SNOWY RIVER,-37.661086,148.361314,0,NaN,JARRAHMOND
9,222201,*,96,96,0,0,0,96,96,0,...,0,0,0,0,SNOWY RIVER,-37.707393,148.450950,0,NaN,ORBOST
10,222202,*,362,355,0,0,0,359,375,0,...,1,0,0,0,BRODRIBB RIVER,-37.511534,148.547325,0,NaN,SARDINE CREEK
11,222206,*,313,308,0,0,0,311,325,0,...,2,0,0,0,BUCHAN RIVER,-37.495843,148.173242,0,NaN,BUCHAN
12,222209,*,361,357,0,0,0,359,373,0,...,0,0,0,0,SNOWY RIVER,-37.083628,148.413255,0,NaN,MCKILLOP BRIDGE
13,222210,*,277,277,0,0,0,276,277,0,...,0,0,0,0,DEDDICK RIVER,-37.085375,148.424152,0,NaN,DEDDICK (CASEYS)
14,222213,*,272,272,0,0,0,272,272,0,...,0,0,0,0,SUGGAN BUGGAN RIVER,-36.955055,148.325921,0,NaN,SUGGAN BUGGAN
15,222217,*,346,338,0,0,0,342,359,0,...,0,0,0,0,RODGER RIVER,-37.410156,148.359867,0,NaN,JACKSONS CROSSING
16,222219,*,175,174,0,0,0,174,179,0,...,0,0,0,0,SNOWY RIVER,-37.499085,148.273625,0,NaN,D/S OF BASIN CREEK
17,223202,*,362,364,0,0,0,362,378,0,...,2,0,0,0,TAMBO RIVER,-37.268781,147.728819,1,"Bream, luderick, flathead, mulloway",SWIFTS CREEK
18,223204,*,346,349,0,0,0,346,362,0,...,0,0,0,0,NICHOLSON RIVER,-37.592946,147.697124,0,NaN,DEPTFORD
19,223205,*,276,276,0,0,0,276,276,0,...,42,0,0,0,TAMBO RIVER,-37.672531,147.869851,1,"Bream, luderick, flathead, mulloway",D/S OF RAMROD CREEK
20,223209,*,17,17,0,0,0,17,17,0,...,0,0,0,0,TAMBO RIVER,-37.757306,147.849116,1,"Bream, luderick, flathead, mulloway",BATTENS LANDING
21,223210,*,627,627,0,0,0,629,681,0,...,0,0,0,0,NICHOLSON RIVER,-37.737562,147.710996,0,NaN,SARSFIELD
22,223212,*,196,196,0,0,0,196,196,0,...,0,0,0,0,TIMBARRA RIVER,-37.446318,148.063434,0,NaN,D/S OF WILKINSON CREEK
23,223214,*,359,361,0,0,0,359,373,0,...,0,0,0,0,TAMBO RIVER,-36.954707,147.927640,1,"Bream, luderick, flathead, mulloway",U/S OF SMITH CREEK
24,223215,*,96,96,0,0,0,96,97,0,...,0,0,0,0,HAUNTED STREAM,-37.481387,147.825839,0,NaN,HELLS GATE
25,224200,*,4,4,0,0,0,4,5,0,...,0,0,0,0,MITCHELL RIVER,-37.826386,147.593617,1,Bream,BAIRNSDALE
26,224201,*,179,179,0,0,0,179,179,0,...,43,0,0,0,WONNANGATTA RIVER,-37.489961,147.166444,0,NaN,WATERFORD
27,224203,*,361,363,0,0,0,361,376,0,...,2,0,0,0,MITCHELL RIVER,-37.763590,147.374778,1,Bream,GLENALADALE
28,224206,*,355,358,0,0,0,358,371,0,...,2,0,0,0,WONNANGATTA RIVER,-37.407497,147.089165,0,NaN,CROOKED RIVER
29,224213,*,358,362,0,0,0,360,375,0,...,0,0,0,0,DARGO RIVER,-37.495118,147.268699,0,NaN,LOWER DARGO ROAD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
388,414716,*,36,35,0,0,0,36,36,0,...,0,0,0,0,ROBINVALE NO 4 SYSTEM OUTFALL,-34.604459,142.740714,0,NaN,PETHARD ROAD
389,414717,*,36,35,0,0,0,36,36,0,...,0,0,0,0,ROBINVALE NO 6 SYSTEM OUTFALL,-34.636635,142.701383,0,NaN,MALAYA ROAD
390,414721,*,24,24,0,0,0,24,24,0,...,0,0,0,0,NANGILOC-COLIGNAN DRAIN,-34.508705,142.380673,0,NaN,HEWETTS ROAD
391,414723,*,23,23,0,0,0,23,23,0,...,0,0,0,0,KULKYNE OUTFALL DRAIN,-34.560305,142.407139,0,NaN,MANSELLS PUMP
392,414724,*,24,24,0,0,0,24,24,0,...,0,0,0,0,NANGILOC COLIGNAN DRAIN,-34.470270,142.353582,0,NaN,NANGILOC
393,414728,*,24,24,0,0,0,24,24,0,...,0,0,0,0,BROWN'S GROUP DRAINAGE AREA,-34.548737,142.388222,0,NaN,BROWN'S ROAD
394,415200,*,363,362,0,0,0,360,363,0,...,2,0,0,0,WIMMERA RIVER,-36.739911,142.147163,0,NaN,HORSHAM
395,415201,*,470,470,0,0,0,470,470,0,...,42,0,0,0,WIMMERA RIVER,-36.909300,142.642970,0,NaN,GLENORCHY WEIR TAIL GAUGE
396,415202,*,153,153,0,0,0,153,174,0,...,0,0,0,0,MACKENZIE RIVER,-37.107641,142.424437,0,NaN,WARTOOK RESERVOIR
397,415203,*,323,325,0,0,0,323,326,0,...,0,0,0,0,MOUNT WILLIAM CREEK,-37.030570,142.583590,0,NaN,LAKE LONSDALE (TAIL GAUGE)
398,415207,*,358,358,0,0,0,357,358,0,...,0,0,0,0,WIMMERA RIVER,-37.185039,143.184627,0,NaN,EVERSLEY
399,415214,*,178,178,0,0,0,178,178,0,...,0,0,0,0,FYANS CREEK,-37.169610,142.542150,0,NaN,LAKE BELLFIELD
400,415217,*,173,173,0,0,0,173,173,0,...,0,0,0,0,FYANS CREEK,-37.250863,142.535748,0,NaN,GRAMPIANS ROAD BRIDGE
401,415220,*,257,257,0,0,0,257,257,0,...,0,0,0,0,AVON RIVER,-36.640580,142.978650,0,NaN,WIMMERA HIGHWAY
402,415227,*,0,0,0,0,0,0,102,0,...,0,0,0,0,MOUNT WILLIAM CREEK,-37.030225,142.586322,0,NaN,LAKE LONSDALE (HEAD GAUGE)
403,415228,*,0,0,0,0,0,3,70,0,...,0,0,0,0,MACKENZIE RIVER,-37.093464,142.434475,0,NaN,WARTOOK RESERVOIR (HEAD GAUGE)
404,415229,*,0,0,0,0,0,3,68,0,...,0,0,0,0,FYANS CREEK,-37.173750,142.547372,0,NaN,LAKE BELLFIELD (HEAD GAUGE)
405,415237,*,275,275,0,0,0,275,276,0,...,0,0,0,0,CONCONGELLA CREEK,-37.025743,142.821776,0,NaN,STAWELL
406,415246,*,335,334,0,0,0,333,335,0,...,0,0,0,0,WIMMERA RIVER,-36.408395,141.974435,0,NaN,LOCHIEL RAILWAY BRIDGE
407,415251,*,210,211,0,0,0,215,210,0,...,0,0,0,0,MACKENZIE RIVER,-36.808231,142.179346,0,NaN,MCKENZIE CREEK
408,415257,*,254,257,0,0,0,254,257,0,...,0,0,0,0,RICHARDSON RIVER,-36.428406,142.984198,0,NaN,DONALD
409,415259,*,164,165,0,0,0,164,164,0,...,0,0,0,0,RICHARDSON RIVER,-36.571321,142.825413,0,NaN,BANYENA
410,415600,*,136,136,0,0,0,128,132,0,...,0,4,0,0,LAKE HINDMARSH,-36.130627,141.954686,0,NaN,JEPARIT
411,415601,*,101,101,0,0,0,101,101,0,...,0,0,0,0,LAKE ALBACUTYA,-35.803196,141.952877,0,NaN,RAINBOW
412,415602,*,63,63,0,0,0,50,59,0,...,0,11,0,0,LAKE NATIMUK,-36.715588,141.940858,0,NaN,HORSHAM
413,415604,*,46,46,0,0,0,46,46,0,...,0,0,0,0,LAKE BULOKE,-36.304300,142.986630,0,NaN,DONALD
414,415608,*,12,12,0,0,0,16,198,0,...,0,0,0,0,TAYLORS LAKE,-36.764681,142.379046,0,NaN,NaN
415,415610,*,0,0,0,0,0,3,185,0,...,0,0,0,0,LAKE FYANS,-37.134804,142.610542,0,NaN,NaN
416,415612,*,0,0,0,0,0,0,119,0,...,0,0,0,0,GREEN LAKE (NEAR HORSHAM),-36.787382,142.290357,0,NaN,NaN
417,426200,*,162,162,0,0,0,162,162,0,...,45,0,0,0,MURRAY RIVER,-34.062193,141.244785,0,NaN,BELOW RUFUS RIVER. OPERATIONAL TABLES

In [7]:
df4.to_csv('final.csv', index=False)